version: "3.7"
services:
  app:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ../    
    tty: true
    volumes:
      - "../:/workspace:cached"
    ports:
      - "8000:8000"